version: '3.1'

services:  

  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Abc12345
      MYSQL_DATABASE: dev_db
    ports:
      - "3307:3306"

  app:
    image: osu-languages-api
    restart: on-failure
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=